# Connection keep alive timeout [default: 75]
keep_alive: 75

# The socket address to bind [default: 0.0.0.0:3000]
listen_addresses: 'localhost:3000'

# Number of web server workers
worker_processes: 8

# Amount of memory (in MB) to use for caching tiles [default: 512, 0 to disable]
cache_size_mb: 512

mbtiles:
    paths:
        - /var/www/victor/tiles/

sprites:
    sources:
        osm-bright: /var/www/victor/public/styles/osm-bright/icons
        fiord: /var/www/victor/public/styles/fiord/icons
        dark-matter: /var/www/victor/public/styles/dark-matter/icons
        positron: /var/www/victor/public/styles/positron/icons

fonts:
    - /var/www/victor/fonts/noto-sans/NotoSans-Bold.ttf
    - /var/www/victor/fonts/noto-sans/NotoSans-Italic.ttf
    - /var/www/victor/fonts/noto-sans/NotoSans-Regular.ttf
    - /var/www/victor/fonts/metropolis/

